name: train

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: [ubuntu-latest]
 
    steps:
      - uses: actions/checkout@v2
 
      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
 
      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.CI_CD_BOSTON_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          python wine.py